openapi: 3.0.4
info:
  title: Barcode Generator
  description: >-
    Barcode Generator is a simple tool for generating barcodes from data. It
    returns a URL to the generated image of the barcode.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/barcodegenerator:
    post:
      summary: Generate Barcode from Data
      description: >-
        Barcode Generator is a simple tool for generating barcodes from data. It
        returns a URL to the generated image of the barcode.
      operationId: barcodegenerator
      parameters: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  imageName: cc85680f-a1d0-4627-89ff-7d7e53663a2b.png
                  format: .png
                  type: CODE128
                  expires: 1766010012598
                  downloadURL: >-
                    https://storage.googleapis.com/apiverve/APIData/barcodegenerator/cc85680f-a1d0-4627-89ff-7d7e53663a2b.png?GoogleAccessId=635500398038-compute%40developer.gserviceaccount.com&Expires=1766010012&Signature=cV6ANXGGaVDdl5SOFZt3xm2haHBnOklW1zXQICvJlGNlF4kwYVP9i%2F1RAN8NBGxSUiMk4Zcro%2FJUb3W%2Fwy8jA86pyEXTwIjNAiGW94ikpKSXs6%2FiV42Rwv6u2gX%2B2FH7XYyixlwJ%2B%2FHpfGcvka6u01FDk%2F2TUcR7%2FxsZ%2FmXPU2KTrzsI6XttCGBcHhex3LdTv%2F8tzMJbSshbZn%2BGcRTddwv6dC4lCcTtGE6Bl2zqY9s92KIr9X%2F4xj34q4XKBzywgXES57QaVhZeGPPOOUfLtI3pAN8fVSyM%2B9NBMU7R46xyqJ0J8PSVpQZhhAHn03T%2B40rcNp26GXqauM9K%2BLwZRw%3D%3D
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: string
                  description: The data you want to generate a barcode from (string)
                type:
                  type: string
                  description: The type of barcode you want to generate
                lineColor:
                  type: string
                  description: 'The color of the barcode (default: #000000)'
                backgroundColor:
                  type: string
                  description: 'The background color of the barcode (default: #ffffff)'
                displayValue:
                  type: boolean
                  description: >-
                    Whether to display the value below the barcode (default:
                    true)
              required:
                - data
                - type
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
sampleRequest:
  data: '51001544700'
  type: code128
  lineColor: '#000000'
  backgroundColor: '#FFFFFF'
  displayValue: true
