name: apiverve_barcodegenerator
description: Barcode Generator is a simple tool for generating barcodes from data. It returns a URL to the generated image of the barcode.
version: 1.1.14
homepage: https://apiverve.com/marketplace/barcodegenerator?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/barcodegenerator-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
